---
# Create bridge interfaces for docker communication

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Check if We are logged in."
      shell: uname -r
      register: out

    - name: print results
      debug: 
        msg: "{{ out.stdout }}"
  
  roles:
    - rnkoaa.ssh
    # - rnkoaa.lockdown

  tasks:
    - name: "Copy br0.netdev"
      copy:
        src: files/br0.netdev
        dest: /etc/systemd/network/br0.netdev
        owner: root
        group: root
        mode: 0744
      become: yes
    
    - name: "Copy br0.netdev"
      copy:
        src: files/br0.network
        dest: /etc/systemd/network/br0.network
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: "Restart systemd-networkd"
      systemd:
        name: systemd-networkd
        daemon_reload: yes
        state: restarted
      become: yes

    - name: "Enable br0 dummy network interface"
      command: ip link set dev br0 up
      become: yes